### ISSUE TITLE
Syntax error 

### ISSUE THREAD

**Issue by lcastanoduque** [boseHere/sRNA_snakemake_workflow#1]
Hello,

I am running the sRNA_snakemake_workflow using an ubuntu cluster.

I was able to get it to run up to the following error:
SyntaxError in line 108 of /work/lmc86/SMALL_RNA/sRNA_snakemake_workflow/Snakefile:
invalid syntax

I checked the Snakefile and line 108 says the following:
	"rm -r data/5_clustered && "

I am unsure about how to fix this issue. Do you have any advice?

All the best,
Lina

**Comment by boseHere** [comment]
Hi Lina,

Sorry about that! It looks like the last version of the file I added was missing a comma at the end of line 107, which is what caused the syntax error on line 108. If you re-download the Snakefile now, that error should be gone.
